 #Ambientes de pruebas
  #spring.datasource.url=jdbc:mysql://localhost:3306/portfolio?allowPublicKeyRetrieval=true&useSSL=false&serverTimezone=UTC
  #spring.datasource.username=root
  #spring.datasource.password=root

#Ambientes de Produccion
  spring.datasource.url=jdbc:mysql://uz0k5qfxfqj0ehvo:5zYjBxbaHAdHmSYobHhn@bzinww7rovqju08lwqqg-mysql.services.clever-cloud.com:3306/bzinww7rovqju08lwqqg
  spring.datasource.username=uz0k5qfxfqj0ehvo
  spring.datasource.password=5zYjBxbaHAdHmSYobHhn
  spring.jpa.hibernate.ddl-auto=update
  spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
  spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
  spring.jpa.show-sql=true

#JWT
jwt.secret = secret
jwt.expiration=3600 
